#ifndef RIG_EXT_API_REF_H
#define RIG_EXT_API_REF_H

static const char *EXT_API_REFERENCE =
"# Rig Extension API Reference\n"
"\n"
"Extensions are Lua 5.4 scripts in .rig/extensions/. Loaded on startup.\n"
"\n"
"## Primitives\n"
"\n"
"rig.exec(cmd, opts?) -> {ok, stdout, exit_code, timed_out}\n"
"  Run shell command. opts.timeout = ms (default 30000).\n"
"\n"
"rig.completion(params) -> string\n"
"  Call LLM. params: {messages, system?, model?, max_tokens?, temperature?}\n"
"  model: substring match, e.g. 'haiku'. Defaults to current model.\n"
"\n"
"rig.print(text, opts?) — display in TUI. opts.error=true for error style.\n"
"\n"
"rig.input(prompt) -> string|nil — block for user input. nil on ctrl+c.\n"
"\n"
"rig.hook(event, fn, priority?) -> handle\n"
"  Events: init, turn_start, pre_api_call, post_api_call, pre_tool, post_tool, turn_end\n"
"  fn(event, data) returns true, false (stop chain), or table (control loop).\n"
"\n"
"rig.unhook(handle) -> bool\n"
"\n"
"rig.get(ns, key?) -> value\n"
"  Namespaces:\n"
"  'config'   -> {model, model_id, provider, context_window, max_output_tokens, cwd}\n"
"  'messages' -> all messages, or: 'count', 'tokens', or integer index (1-based)\n"
"  'prompts'  -> system prompt string, or 'tokens' for token estimate\n"
"  'tools'    -> tool names array, or tool name -> {name, description}\n"
"  'settings' -> settings value by key\n"
"  'state'    -> extension state value by key\n"
"\n"
"rig.set(ns, key, value)\n"
"  'tools'    -> register: {description, params, run=fn}. nil to remove.\n"
"  'commands' -> register slash command: fn(args)\n"
"  'messages' -> 'append' {role,content}, 'clear', 'splice' {start,delete,messages}\n"
"  'prompts'  -> key,text to inject fragment. key,nil to remove.\n"
"  'settings' -> set value\n"
"  'state'    -> set value (persisted across restarts)\n"
"\n"
"rig.read_file(path) -> string|nil, error\n"
"  Read file contents. 10MB limit. Returns nil+error on failure.\n"
"\n"
"rig.write_file(path, content) -> bool\n"
"  Write file. Returns true on success.\n"
"\n"
"rig.publish(topic, data) — publish to event bus.\n"
"rig.subscribe(topic, fn) — subscribe. fn(topic, data).\n"
"\n"
"rig.spawn(cmd) -> process handle\n"
"  Start persistent subprocess. Methods:\n"
"  proc:write(str) -> bool\n"
"  proc:read_line(timeout_ms?) -> string|nil (default 30000ms)\n"
"  proc:is_alive() -> bool\n"
"  proc:close()\n"
"\n"
"rig.select(items, initial?) -> string|nil\n"
"  Arrow-key selector menu. Returns chosen item or nil on cancel.\n"
"\n"
"json.encode(table) -> string\n"
"json.decode(string) -> table\n"
"\n"
"## Hook Return Values\n"
"\n"
"pre_api_call can return: {abort=true}, {skip=true}, {max_tokens=N}, {temperature=N}\n"
"pre_tool can return: {block=true, reason='...'}, {modify_args={...}}\n"
"post_tool can return: {override_result='...'}\n"
"turn_end can return: {continue_loop=true}, {inject_messages={{role,content},...}}\n"
"\n"
"## Message Splicing\n"
"\n"
"rig.set('messages', 'splice', {start=N, delete=N, messages={{role,content},...}})\n"
"  start: 1-indexed position. delete: number to remove. messages: replacements.\n"
"  Cannot splice while streaming.\n"
"\n"
"## Extension Surfaces\n"
"\n"
"Extensions expose functionality through:\n"
"1. Slash commands: rig.set('commands', 'name', fn) — user types /name\n"
"2. Tools: rig.set('tools', 'name', {description, params, run}) — model calls it\n"
"3. Hooks: rig.hook('event', fn) — automatic triggers\n"
"\n"
"## Sandbox\n"
"\n"
"os, io, loadfile, dofile, debug are removed.\n"
"Use rig.exec() for shell, rig.read_file()/rig.write_file() for files.\n"
"Memory limit: 50MB. Instruction limit: 100M ops.\n"
"\n"
"## Example: MCP server integration\n"
"\n"
"local proc = rig.spawn('npx @modelcontextprotocol/server-files /home')\n"
"proc:write(json.encode({jsonrpc='2.0',id=1,method='initialize',params={}})..'\\n')\n"
"local resp = json.decode(proc:read_line(10000))\n"
"-- Register tools from resp.result.capabilities.tools\n";

#endif
